AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/**/*
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
