version: '3'

services:
  website: 
    build:
      context: .
    command: tail -f /dev/null
    ports: 
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1

  redis:
    image: redis:5-alpine3.9
    volumes:
      - vol_redis_cache:/data

volumes:
  gem_cache:
  vol_redis_cache:
