version: '3'

services:
  website: 
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1

volumes:
  gem_cache:
