version: '3'

services:
  website: 
    build:
      context: .
    command: tail -f /dev/null
    ports:
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
      BUNDLE_PATH: /app/vendor/bundle

  redis:
    image: redis:5-alpine3.9
    volumes:
      - vol_redis_cache:/data

volumes:
  vol_redis_cache:
