version: '3'

services:
  website:
    build:
      context: .
    depends_on:
      - db
      - redis
      - sidekiq
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - env.web

  sidekiq:
    build:
      context: .
    command: ["sidekiq", "-C", "config/sidekiq.yml"]
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - env.web

  redis:
    image: redis:5-alpine3.9
    volumes:
      - vol_redis_cache:/data

  db:
    image: mariadb:10.5.5
    volumes:
      - vol_mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password

volumes:
  vol_redis_cache:
  vol_mysql:
